apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 40691
      targetPort: 40691
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
data:
  client-to-send-per-replica: "100_000"
  client-worker-count: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: client
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: client
          image: client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DUMMY_PORT
              valueFrom:
                configMapKeyRef:
                  name: dummy-configmap
                  key: dummy-port
            - name: CLIENT_TO_SEND
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: client-to-send-per-replica
            - name: CLIENT_WORKER_COUNT
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: client-worker-count
            - name: OTEL_COLLECTOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: otel-configmap
                  key: otel-collector-host