global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'sql-distributed-transactions-server'
    static_configs:
      - targets: [ 'server:40690' ]

remote_write:
  - url: http://mimir:9009/api/v1/push