global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:9090']

remote_write:
  - url: http://mimir:9009/api/v1/push