apiVersion: v1
kind: Service
metadata:
  name: mimir
spec:
  selector:
    app: mimir
  ports:
    - protocol: TCP
      port: 9009
      targetPort: 9009
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mimir
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/mimir
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
spec:
  selector:
    matchLabels:
      app: mimir
  serviceName: mimir
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mimir
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mimir
          image: grafana/mimir:2.17.0
          args:
            - -config.file=/etc/mimir.yaml
          ports:
            - containerPort: 9009
          volumeMounts:
            - name: mimir-config-yaml
              mountPath: /etc
              readOnly: true
            - name: mimir
              mountPath: /data
      volumes:
        - name: mimir-config-yaml
          configMap:
            name: mimir-config-yaml-configmap
  volumeClaimTemplates:
    - metadata:
        name: mimir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi