apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: http
      protocol: TCP
      port: 3200
      targetPort: http
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/tempo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
spec:
  selector:
    matchLabels:
      app: tempo
  serviceName: tempo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: tempo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: tempo
          image: grafana/tempo:2.8.2
          args:
            - -config.file=/etc/tempo/tempo.yaml
          ports:
            - name: http
              containerPort: 3200
            - name: otlp-grpc
              containerPort: 4317
          volumeMounts:
            - name: tempo-config-yaml
              mountPath: /etc/tempo
              readOnly: true
            - name: tempo
              mountPath: /var/tempo
      volumes:
        - name: tempo-config-yaml
          configMap:
            name: tempo-config-yaml-configmap
  volumeClaimTemplates:
    - metadata:
        name: tempo
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi