apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  selector:
    matchLabels:
      app: loki
  serviceName: loki
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: loki
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: loki
          image: grafana/loki:3.5.3
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config-yaml
              mountPath: /etc/loki
              readOnly: true
            - name: loki
              mountPath: /loki/wal
      volumes:
        - name: loki-config-yaml
          configMap:
            name: loki-config-yaml-configmap
  volumeClaimTemplates:
    - metadata:
        name: loki
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi