apiVersion: v1
kind: Service
metadata:
  name: server-psql
spec:
  selector:
    app: server-psql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: server-psql-secret
type: Opaque
stringData:
  user: "postgres"
  password: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-psql-configmap
data:
  db: "coordinator"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-psql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/server-psql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-psql
spec:
  selector:
    matchLabels:
      app: server-psql
  serviceName: server-psql
  replicas: 1
  template:
    metadata:
      labels:
        app: server-psql
    spec:
      containers:
        - name: server-psql
          image: postgres:17.4-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: server-psql-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-psql-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: server-psql-configmap
                  key: db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: server-psql
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: server-psql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi